enjalot/blockbuilder

- public/js/components/app.js
- public/js/components/home.js
- public/js/components/not-found.js
- public/js/components/user.js
quick update to logging group names, prefixing group names with `component`
> updates group names for components

- .gitignore
- README.md
- secrets.json-example
let me know if there are any changes to be made.
thx!
> made description more newbie-friendly

- README.md
- public/js/components/files.js
- server.js
Adds key to FilesTab component ( see:https://facebook.github.io/react/docs/multiple-components.html#dynamic-children ), adds a little helper message when booting up server for people that skip the readme
> Minor update to add key prop

- README.md
- deploy/README.md
- npm-debug.log
- package.json
Adds more meaningful names for NPM scripts
> Updates readme, updates npm scripts

- deploy/building-blocks.conf
> updates building blocks deploy scripts

- Makefile
- deploy/README.md
Creates a single makefile command which can be called when updating data to ensure dependencies are  up to date
> Updates deploy notes and makefile

- public/js/components/editor__error-marker.js
- public/js/components/editor__html.js
- public/js/utils/parseCode.js
to fix https://github.com/enjalot/building-blocks/issues/59
> line errors working

- public/js/components/editor__html.js
Some extra color when html editor is in an error state.  Implementation is hacky, but it shows what it can look like.
> Extracolor

- views/base.handlebars
Hi,
I have noticed that d3js is loading twice on the production site so i removed one of them.  
Peace!
> Remove duplicated d3js script load

- views/base.handlebars
It looks like this css import is not necessary OR `htaccess` is configured in such a way that it never gets to the actual file.
Output from curl to production version of this url (`curl --url http://blockbuilder.org/css/style.css\?20150720`):
```
<!DOCTYPE html>
<meta charset="utf-8">
<title>Building Bl.ocks</title>
<link href='http://fonts.googleapis.com/css?family=Roboto:400,700,400italic|Open+Sans:400italic,400,700' rel='stylesheet' type='text/css'>
<style>
@import url("/css/style.css?20150720");
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.4.0/codemirror.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.4.0/theme/twilight.css">
<link rel="stylesheet" …
```
> Remove unnecessary stylesheet import

- views/base.handlebars
Based on http://codemirror.net/doc/releases.html and my localhost shallow testing it should not blow up :)
I believe marked is using semver for versioning, if im right, third number should not break existing apps either.
> Update CodeMirror and Marked dependencies

- views/base.handlebars
Quickly fixed my mistake.
This is continuation of https://github.com/enjalot/building-blocks/pull/82
> html: closed head tag, opened body tag, added indentation

- public/css/main.scss
- public/js/components/home.js
Couple cosmetic changes, some visible at first sight, some not.
Let me know what do you think about the direction.
> Improve readability, typography

- resources.json
- server.js
Would be nice to run redis/mongodb on other hosts/ports!
> Break out external resources to a config file

- public/js/components/header__nav-gist.js
Is this what you are looking for @stelt in #137 ?
> swapping the description with the site name

- .eslintrc.yml
- package.json
This is a proposition to introduce some sort of code style to improve readability and hopefully code quality in general. Everyone with eslint plugin in their code editor should see eslint feedback thanks to `.eslintrc` file.
If this is a good idea and this PR will be merged as a followup i can go through every js file and apply sensible rules to the code and list (to discuss) those that does not make a lot of sense in this particular project. This excercise should allow us to work out custom code style that works best in current environment.
> Add eslint

- views/base.handlebars
> Load minified version of inlet.js

- public/js/components/editor__html.js
Seems like CodeMirror supports configuration of script types in mixedhtml mode :)
Proposal for #129 & #130
> Added support for <script type="text/babel">

- .eslintrc.yml
- package.json
- public/js/components/about.js
- public/js/components/backers.js
- public/js/components/block.js
- public/js/components/editor.js
- public/js/components/editor__png.js
- public/js/components/files__add.js
- public/js/components/files__tab.js
- public/js/components/gallery.js
- public/js/components/header__nav-save-fork.js
- public/js/components/home.js
- public/js/components/keyboard-shortcuts.js
- public/js/components/renderer.js
- public/js/components/user.js
Comment out some console.logs on client side
Remove unnecessary imports of unused modules
Add one FIX note - potentially throwing JS error ATM
Those changes should further ease up the process of improving code style/quality in the project.
> Add eslint-plugin-react and enable linting JSX

- public/js/components/header__nav-user.js
I liked the idea proposed in #163 so I created this PR.
Fixes #163
> [#163] Link user avatar to his/her blocks on search page

- public/js/utils/parseCode.js
fix #192 
**before**
**after**
> put the DOCTYPE at the top of the compiled index.html for the user

- server.js
This PR ports the comment text from the github issue comment into a proper code comment and adds a link to the `blockbuilder-search` project https://github.com/enjalot/blockbuilder-search
> complete comment about blockbuilder search in server.js fix #177

- public/js/components/renderer.js
> remove deprecated allowvr iframe attribute

- package.json
Closes #218.
See also
* Code change in `magic-sandbox`: https://github.com/datavis-tech/magic-sandbox/pull/8
*  `magic-sandbox` v1.1.0 release: https://github.com/datavis-tech/magic-sandbox/releases/tag/v1.1.0
> Add fetch support
